# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 403aabb4a76dc048948ecc9e5db23630453dfbd12d5f26839fa517e5771f40f6abbc07649bf546cd31868c0fad14a28328ea711c1f42d4db5862585a38a63c07

test:
  secret_key_base: 590d04f9cbf715db6f34101b17db7144f869d4a77dd2e3a63775773d4daadecd82d700abf8258797f2a26cd1df7ab7c4ffa66288af9a9fcef519d9067eccec83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
